// Configuration for artifacts and perk mappings
const artifactsConfig = {
  // Whitelist of all artifacts
  artifacts: [
    "The Butcher",
    "Wit",
    "Freya's Francisca",
    "Sin",
    "Trsna",
    "Spark of Mjölnir",
    "The Abyss",
    "Tempest Fury",
    "Serenity",
    "Scorpion's Sting",
    "Finisher",
    "Boltcaster",
    "Pestilence",
    "Inferno",
    "Deep Freeze",
    "Lifetaker",
    "Void Darkplate",
    "Survivor's Coat",
    "Magnetic Gauntlets",
    "Cowl of Power",
    "Grey Wizard's Hat",
    "Nimble Coat",
    "Azoth Conductors",
    "Ironheart",
    "Freedom",
    "Ankh",
    "Blood Drinker",
    "Phoenix",
    "Endless Thirst",
    "Lost Stopwatch",
    "Elemental Band"
  ],

  // Perk to craft mod URL mappings
  perkCraftMods: {
    // Armor perks
    "Enchanted Ward": "https://nwdb.info/db/perk/perkid_armor_defbasic",
    "Elemental Ward": "https://nwdb.info/db/perk/perkid_armor_defelemental",
    "Physical Ward": "https://nwdb.info/db/perk/perkid_armor_defphysical",
    "Elemental Aversion": "https://nwdb.info/db/perk/perkid_armor_defelementalaversion",
    "Physical Aversion": "https://nwdb.info/db/perk/perkid_armor_defphysicalaversion",
    "Refreshing": "https://nwdb.info/db/perk/perkid_armor_refreshing",
    "Refreshing Ward": "https://nwdb.info/db/perk/perkid_armor_refreshingward",
    "Refreshing Evasion": "https://nwdb.info/db/perk/perkid_armor_refreshingevasion",
    "Invigorated": "https://nwdb.info/db/perk/perkid_armor_invigorated",
    "Invigorated Punishment": "https://nwdb.info/db/perk/perkid_armor_invigoratedpunishment",
    "Invigorated Ward": "https://nwdb.info/db/perk/perkid_armor_invigoratedward",
    "Invigorated Evasion": "https://nwdb.info/db/perk/perkid_armor_invigoratedevasion",
    "Resilient": "https://nwdb.info/db/perk/perkid_armor_resilient",
    "Freedom": "https://nwdb.info/db/perk/perkid_armor_freedom",
    "Vigor": "https://nwdb.info/db/perk/perkid_armor_vigor",
    "Health": "https://nwdb.info/db/perk/perkid_armor_health",
    "Divine": "https://nwdb.info/db/perk/perkid_armor_divine",
    "Divine Blessing": "https://nwdb.info/db/perk/perkid_armor_divineblessing",
    "Divine Ward": "https://nwdb.info/db/perk/perkid_armor_divineward",
    "Divine Evasion": "https://nwdb.info/db/perk/perkid_armor_divineevasion",
    "Shirking Elemental": "https://nwdb.info/db/perk/perkid_armor_shirkingelemental",
    "Shirking Physical": "https://nwdb.info/db/perk/perkid_armor_shirkingphysical",
    "Shirking Fortification": "https://nwdb.info/db/perk/perkid_armor_shirkingfortification",
    "Shirking Heals": "https://nwdb.info/db/perk/perkid_armor_shirkingheals",
    "Shirking Energy": "https://nwdb.info/db/perk/perkid_armor_shirkingenergy",
    "Shirking Abyss": "https://nwdb.info/db/perk/perkid_armor_shirkingabyss",
    "Shirking Nature": "https://nwdb.info/db/perk/perkid_armor_shirkingnature",
    "Shirking Void": "https://nwdb.info/db/perk/perkid_armor_shirkingvoid",
    "Shirking Ice": "https://nwdb.info/db/perk/perkid_armor_shirkingice",
    "Shirking Fire": "https://nwdb.info/db/perk/perkid_armor_shirkingfire",
    "Shirking Lightning": "https://nwdb.info/db/perk/perkid_armor_shirkinglightning",
    "Shirking Arcane": "https://nwdb.info/db/perk/perkid_armor_shirkingarcane",
    "Shirking Strike": "https://nwdb.info/db/perk/perkid_armor_shirkingstrike",
    "Shirking Rend": "https://nwdb.info/db/perk/perkid_armor_shirkingrend",
    "Shirking Empower": "https://nwdb.info/db/perk/perkid_armor_shirkingempower",
    "Shirking Breach": "https://nwdb.info/db/perk/perkid_armor_shirkingbreach",
    "Shirking Snare": "https://nwdb.info/db/perk/perkid_armor_shirkingsnare",
    "Shirking Frost": "https://nwdb.info/db/perk/perkid_armor_shirkingfrost",
    "Shirking Flame": "https://nwdb.info/db/perk/perkid_armor_shirkingflame",
    "Shirking Shock": "https://nwdb.info/db/perk/perkid_armor_shirkingstock",
    "Shirking Thorns": "https://nwdb.info/db/perk/perkid_armor_shirkingthorns",
    "Shirking Empowered": "https://nwdb.info/db/perk/perkid_armor_shirkingempowered",
    "Shirking Void Strike": "https://nwdb.info/db/perk/perkid_armor_shirkingvoidstrike",
    "Shirking Void Rend": "https://nwdb.info/db/perk/perkid_armor_shirkingvoidrend",
    "Shirking Void Empower": "https://nwdb.info/db/perk/perkid_armor_shirkingvoidempower",
    "Shirking Void Breach": "https://nwdb.info/db/perk/perkid_armor_shirkingvoidbreach",
    "Shirking Void Snare": "https://nwdb.info/db/perk/perkid_armor_shirkingvoidsnare",
    "Shirking Void Frost": "https://nwdb.info/db/perk/perkid_armor_shirkingvoidfrost",
    "Shirking Void Flame": "https://nwdb.info/db/perk/perkid_armor_shirkingvoidflame",
    "Shirking Void Shock": "https://nwdb.info/db/perk/perkid_armor_shirkingvoidstock",
    "Shirking Void Thorns": "https://nwdb.info/db/perk/perkid_armor_shirkingvoidthorns",
    "Shirking Void Empowered": "https://nwdb.info/db/perk/perkid_armor_shirkingvoidempowered",
    
    // Weapon perks
    "Enchanted": "https://nwdb.info/db/perk/perkid_weapon_enchanted",
    "Keen": "https://nwdb.info/db/perk/perkid_weapon_keen",
    "Keenly Jagged": "https://nwdb.info/db/perk/perkid_weapon_keenlyjagged",
    "Keenly Empowered": "https://nwdb.info/db/perk/perkid_weapon_keenlyempowered",
    "Keenly Fortified": "https://nwdb.info/db/perk/perkid_weapon_keenlyfortified",
    "Keenly Aware": "https://nwdb.info/db/perk/perkid_weapon_keenlyaware",
    "Keenly Swift": "https://nwdb.info/db/perk/perkid_weapon_keenlyswift",
    "Keenly Jagged": "https://nwdb.info/db/perk/perkid_weapon_keenlyjagged",
    "Keenly Empowered": "https://nwdb.info/db/perk/perkid_weapon_keenlyempowered",
    "Keenly Fortified": "https://nwdb.info/db/perk/perkid_weapon_keenlyfortified",
    "Keenly Aware": "https://nwdb.info/db/perk/perkid_weapon_keenlyaware",
    "Keenly Swift": "https://nwdb.info/db/perk/perkid_weapon_keenlyswift",
    "Vicious": "https://nwdb.info/db/perk/perkid_weapon_vicious",
    "Mortal Power": "https://nwdb.info/db/perk/perkid_weapon_mortalpower",
    "Mortal Lifesteal": "https://nwdb.info/db/perk/perkid_weapon_mortallifesteal",
    "Mortal Siphoning": "https://nwdb.info/db/perk/perkid_weapon_mortalsiphoning",
    "Mortal Energy": "https://nwdb.info/db/perk/perkid_weapon_mortalenergy",
    "Mortal Refresh": "https://nwdb.info/db/perk/perkid_weapon_mortalrefresh",
    "Mortal Empowerment": "https://nwdb.info/db/perk/perkid_weapon_mortalempowerment",
    "Mortal Fortification": "https://nwdb.info/db/perk/perkid_weapon_mortalfortification",
    "Mortal Awareness": "https://nwdb.info/db/perk/perkid_weapon_mortalawareness",
    "Mortal Swiftness": "https://nwdb.info/db/perk/perkid_weapon_mortalswiftness",
    "Mortal Jagged": "https://nwdb.info/db/perk/perkid_weapon_mortaljagged",
    "Mortal Lifesteal": "https://nwdb.info/db/perk/perkid_weapon_mortallifesteal",
    "Mortal Siphoning": "https://nwdb.info/db/perk/perkid_weapon_mortalsiphoning",
    "Mortal Energy": "https://nwdb.info/db/perk/perkid_weapon_mortalenergy",
    "Mortal Refresh": "https://nwdb.info/db/perk/perkid_weapon_mortalrefresh",
    "Mortal Empowerment": "https://nwdb.info/db/perk/perkid_weapon_mortalempowerment",
    "Mortal Fortification": "https://nwdb.info/db/perk/perkid_weapon_mortalfortification",
    "Mortal Awareness": "https://nwdb.info/db/perk/perkid_weapon_mortalawareness",
    "Mortal Swiftness": "https://nwdb.info/db/perk/perkid_weapon_mortalswiftness",
    "Mortal Jagged": "https://nwdb.info/db/perk/perkid_weapon_mortaljagged",
    
    // Add more perk mappings as needed...
  },

  // Gem slot identifiers
  gemSlots: [
    "Elemental Ward",
    "Elemental Ward II",
    "Elemental Ward III", 
    "Elemental Ward IV",
    "Elemental Ward V",
    "Physical Ward",
    "Physical Ward II",
    "Physical Ward III",
    "Physical Ward IV",
    "Physical Ward V",
    "Arcane Ward",
    "Arcane Ward II", 
    "Arcane Ward III",
    "Arcane Ward IV",
    "Arcane Ward V",
    "Nature Ward",
    "Nature Ward II",
    "Nature Ward III",
    "Nature Ward IV", 
    "Nature Ward V",
    "Fire Ward",
    "Fire Ward II",
    "Fire Ward III",
    "Fire Ward IV",
    "Fire Ward V",
    "Ice Ward",
    "Ice Ward II",
    "Ice Ward III",
    "Ice Ward IV",
    "Ice Ward V",
    "Lightning Ward",
    "Lightning Ward II",
    "Lightning Ward III",
    "Lightning Ward IV",
    "Lightning Ward V",
    "Void Ward",
    "Void Ward II",
    "Void Ward III",
    "Void Ward IV",
    "Void Ward V"
  ]
};

module.exports = artifactsConfig; 